### PR TITLE
chore: tweak simulation ergonomics

### PR DESCRIPTION
**Pull request by silasbw**
This new approach handles cases where networks aren't supported and when simulation fails for some reason.

### CODE REVIEW

**Comment by silasbw** [comment]
I'll fix tests if folks prefer the approach in the PR over the existing one.

**Review by jeanregisser — COMMENTED** [review]
Yeah this looks good!

One question, are we later planning to move this out of the shortcut `onTrigger` implementation?

The code calling `onTrigger` could take care of the simulation, without the hook definition calling it explicitly.
Maybe we'd add a `fallbackGas` that hooks authors could define.

**Comment by silasbw** [comment]
Yes, the plan is to move it out of the `onTrigger` implementation eventually. I was unsure about the assumptions we'd make/contract we'd have for doing so.

For example: https://github.com/valora-inc/hooks/blob/main/src/apps/aave/shortcuts.ts#L104-L109

What if there are more than two serialized transactions?  What if there's some combination of concurrent and serialized transactions?  What if I'm just overthinking?

**Comment by jeanregisser** [comment]
I see, I'm fine trying our best guess here, directly outside of the shortcut definition.
It would work similarly for `N` TXs I think.

**Comment by silasbw** [comment]
OK -- I can do that in a follow on!

**Review by jeanregisser — APPROVED** [review]

**Pull request merged**
